export const LogAction = {

	//SysTab信息
	minorType : '2',
	aliasTabName : '操作日志',
	tabName : 'log_action',
	majorType : '10201',

	//SysFld信息
	sysFld: [
	{
		aliasColName : '内部ID',
		dispOrder : '1',
		addController : '0',
		queryController : '0',
		nullable : '0',
		dispType : '1',
		showController : '0',
		tabName : 'log_action',
		dataType : '5',
		colName : 'id',
		editController : '0',
	}, {
		aliasColName : '操作',
		dispOrder : '2',
		addController : '2',
		queryController : '2',
		nullable : '0',
		dispType : '3',
		showController : '1',
		tabName : 'log_action',
		dataType : '5',
		colName : 'action',
		editController : '2',
	}, {
		aliasColName : '描述',
		dispOrder : '3',
		addController : '2',
		queryController : '2',
		nullable : '0',
		dispType : '1',
		showController : '1',
		tabName : 'log_action',
		dataType : '1',
		colName : 'description',
		editController : '2',
	}, {
		aliasColName : '用户',
		dispOrder : '4',
		addController : '2',
		queryController : '2',
		nullable : '0',
		dispType : '1',
		showController : '1',
		tabName : 'log_action',
		dataType : '1',
		colName : 'username',
		editController : '2',
	}, {
		aliasColName : '模块',
		dispOrder : '5',
		addController : '2',
		queryController : '2',
		nullable : '0',
		dispType : '1',
		showController : '1',
		tabName : 'log_action',
		dataType : '1',
		colName : 'modulename',
		editController : '2',
	}, {
		aliasColName : '状态',
		dispOrder : '6',
		addController : '2',
		queryController : '2',
		nullable : '0',
		dispType : '3',
		showController : '1',
		tabName : 'log_action',
		dataType : '5',
		colName : 'status',
		editController : '2',
	}, {
		aliasColName : '时间',
		dispOrder : '7',
		addController : '2',
		queryController : '2',
		nullable : '0',
		dispType : '4',
		showController : '1',
		tabName : 'log_action',
		dataType : '401',
		colName : 'date',
		editController : '2',
	}],

	//SysFldVal信息
	sysFldVal: {
		action: [
		{
			dispOrder : 1,
			dbVal : 1,
			tabName : 'log_action',
			colName : 'action',
			dispVal : '新增',
		}, {
			dispOrder : 2,
			dbVal : 2,
			tabName : 'log_action',
			colName : 'action',
			dispVal : '修改',
		}, {
			dispOrder : 3,
			dbVal : 3,
			tabName : 'log_action',
			colName : 'action',
			dispVal : '删除',
		}, {
			dispOrder : 4,
			dbVal : 4,
			tabName : 'log_action',
			colName : 'action',
			dispVal : '登陆',
		}],
		status: [
		{
			dispOrder : 1,
			dbVal : 1,
			tabName : 'log_action',
			colName : 'status',
			dispVal : '成功',
		}, {
			dispOrder : 2,
			dbVal : 2,
			tabName : 'log_action',
			colName : 'status',
			dispVal : '失败',
		}],
	},
};