export const LogRequest = {

	//SysTab信息
	minorType : '3',
	aliasTabName : '请求日志',
	tabName : 'log_request',
	majorType : '10201',

	//SysFld信息
	sysFld: [
	{
		aliasColName : '内部ID',
		dispOrder : '1',
		addController : '0',
		queryController : '0',
		nullable : '0',
		dispType : '1',
		showController : '0',
		tabName : 'log_request',
		dataType : '5',
		colName : 'id',
		editController : '0',
	}, {
		aliasColName : '服务名称',
		dispOrder : '2',
		addController : '2',
		queryController : '2',
		nullable : '0',
		dispType : '1',
		showController : '1',
		tabName : 'log_request',
		dataType : '1',
		colName : 'servername',
		editController : '2',
	}, {
		aliasColName : '请求方式',
		dispOrder : '3',
		addController : '2',
		queryController : '2',
		nullable : '0',
		dispType : '1',
		showController : '1',
		tabName : 'log_request',
		dataType : '1',
		colName : 'method',
		editController : '2',
	}, {
		aliasColName : '请求地址',
		dispOrder : '4',
		addController : '2',
		queryController : '2',
		nullable : '0',
		dispType : '1',
		showController : '1',
		tabName : 'log_request',
		dataType : '1',
		colName : 'remoteaddr',
		editController : '2',
	}, {
		aliasColName : '请求用户',
		dispOrder : '5',
		addController : '2',
		queryController : '2',
		nullable : '0',
		dispType : '1',
		showController : '1',
		tabName : 'log_request',
		dataType : '1',
		colName : 'remoteuser',
		editController : '2',
	}, {
		aliasColName : '请求主机',
		dispOrder : '6',
		addController : '2',
		queryController : '2',
		nullable : '0',
		dispType : '1',
		showController : '1',
		tabName : 'log_request',
		dataType : '1',
		colName : 'remotehost',
		editController : '2',
	}, {
		aliasColName : '请求uri',
		dispOrder : '7',
		addController : '2',
		queryController : '2',
		nullable : '0',
		dispType : '1',
		showController : '1',
		tabName : 'log_request',
		dataType : '1',
		colName : 'requesturi',
		editController : '2',
	}, {
		aliasColName : '请求ip',
		dispOrder : '8',
		addController : '2',
		queryController : '2',
		nullable : '0',
		dispType : '1',
		showController : '1',
		tabName : 'log_request',
		dataType : '1',
		colName : 'requestip',
		editController : '2',
	}, {
		aliasColName : '时间',
		dispOrder : '9',
		addController : '2',
		queryController : '2',
		nullable : '0',
		dispType : '4',
		showController : '1',
		tabName : 'log_request',
		dataType : '401',
		colName : 'date',
		editController : '2',
	}],

	//SysFldVal信息
	sysFldVal: {
	},
};