export const PmsnUser = {

	//SysTab信息
	minorType : '2',
	aliasTabName : '用户',
	tabName : 'pmsn_user',
	majorType : '10401',
	assoMajor : '10401',
	assoMinor : '3',

	//SysFld信息
	sysFld: [
	{
		aliasColName : '用户id',
		dispOrder : '1',
		addController : '0',
		queryController : '0',
		nullable : '0',
		dispType : '1',
		showController : '0',
		tabName : 'pmsn_user',
		dataType : '5',
		colName : 'id',
		editController : '0',
	}, {
		aliasColName : '登陆名',
		dispOrder : '2',
		addController : '2',
		queryController : '0',
		nullable : '0',
		dispType : '1',
		showController : '1',
		tabName : 'pmsn_user',
		dataType : '1',
		colName : 'login_name',
		editController : '1',
	}, {
		aliasColName : '用户名',
		dispOrder : '3',
		addController : '2',
		queryController : '2',
		nullable : '0',
		dispType : '1',
		showController : '1',
		tabName : 'pmsn_user',
		dataType : '1',
		colName : 'user_name',
		editController : '2',
	}, {
		aliasColName : '密码',
		dispOrder : '4',
		addController : '0',
		queryController : '0',
		nullable : '0',
		dispType : '102',
		showController : '0',
		tabName : 'pmsn_user',
		dataType : '1',
		colName : 'password',
		editController : '0',
	}, {
		aliasColName : '办公电话',
		dispOrder : '5',
		addController : '2',
		queryController : '2',
		nullable : '1',
		dispType : '105',
		showController : '1',
		tabName : 'pmsn_user',
		dataType : '1',
		colName : 'tel',
		editController : '2',
	}, {
		aliasColName : '手机号',
		dispOrder : '6',
		addController : '2',
		queryController : '2',
		nullable : '1',
		dispType : '105',
		showController : '1',
		tabName : 'pmsn_user',
		dataType : '1',
		colName : 'mobile',
		editController : '2',
	}, {
		aliasColName : '邮箱',
		dispOrder : '7',
		addController : '2',
		queryController : '2',
		nullable : '1',
		dispType : '103',
		showController : '1',
		tabName : 'pmsn_user',
		dataType : '1',
		colName : 'email',
		editController : '2',
	}, {
		aliasColName : '所属部门',
		dispOrder : '8',
		addController : '2',
		queryController : '2',
		nullable : '0',
		dispType : '302',
		showController : '1',
		tabName : 'pmsn_user',
		dataType : '5',
		colName : 'asso_id',
		editController : '1',
	}, {
		aliasColName : '启用状态',
		dispOrder : '9',
		addController : '2',
		queryController : '2',
		nullable : '0',
		dispType : '3',
		showController : '1',
		tabName : 'pmsn_user',
		dataType : '5',
		colName : 'enable',
		editController : '2',
	}, {
		aliasColName : '头像',
		dispOrder : '10',
		addController : '0',
		queryController : '0',
		nullable : '0',
		dispType : '1',
		showController : '0',
		tabName : 'pmsn_user',
		dataType : '1',
		colName : 'image',
		editController : '0',
	}],

	//SysFldVal信息
	sysFldVal: {
		enable: [
		{
			dispOrder : 1,
			dbVal : 1,
			tabName : 'pmsn_user',
			colName : 'enable',
			dispVal : '启用',
		}, {
			dispOrder : 2,
			dbVal : 0,
			tabName : 'pmsn_user',
			colName : 'enable',
			dispVal : '不启用',
		}],
	},
};