export const SysMenu = {

	//SysTab信息
	minorType : '2',
	aliasTabName : '菜单表',
	tabName : 'sys_menu',
	majorType : '10102',

	//SysFld信息
	sysFld: [
	{
		aliasColName : '菜单ID',
		dispOrder : '1',
		addController : '1',
		queryController : '0',
		nullable : '0',
		dispType : '1',
		showController : '0',
		tabName : 'sys_menu',
		dataType : '5',
		colName : 'id',
		editController : '0',
	}, {
		aliasColName : '上级ID',
		dispOrder : '2',
		addController : '2',
		queryController : '0',
		nullable : '1',
		dispType : '1',
		showController : '0',
		tabName : 'sys_menu',
		dataType : '5',
		colName : 'super_id',
		editController : '2',
	}, {
		aliasColName : '级别',
		dispOrder : '3',
		addController : '0',
		queryController : '0',
		nullable : '1',
		dispType : '1',
		showController : '0',
		tabName : 'sys_menu',
		dataType : '5',
		colName : 'level_type',
		editController : '0',
	}, {
		aliasColName : '标题',
		dispOrder : '4',
		addController : '2',
		queryController : '2',
		nullable : '0',
		dispType : '1',
		showController : '1',
		tabName : 'sys_menu',
		dataType : '1',
		colName : 'title',
		editController : '2',
	}, {
		aliasColName : '链接地址',
		dispOrder : '5',
		addController : '2',
		queryController : '0',
		nullable : '1',
		dispType : '1',
		showController : '1',
		tabName : 'sys_menu',
		dataType : '1',
		colName : 'url',
		editController : '2',
	}, {
		aliasColName : '响应函数',
		dispOrder : '6',
		addController : '2',
		queryController : '0',
		nullable : '1',
		dispType : '1',
		showController : '1',
		tabName : 'sys_menu',
		dataType : '1',
		colName : 'click',
		editController : '2',
	}, {
		aliasColName : '类型',
		dispOrder : '7',
		addController : '2',
		queryController : '2',
		nullable : '0',
		dispType : '3',
		showController : '1',
		tabName : 'sys_menu',
		dataType : '5',
		colName : 'type',
		editController : '2',
	}, {
		aliasColName : '菜单模版类型',
		dispOrder : '8',
		addController : '2',
		queryController : '1',
		nullable : '1',
		dispType : '3',
		showController : '1',
		tabName : 'sys_menu',
		dataType : '5',
		colName : 'menu_type',
		editController : '2',
	}, {
		aliasColName : '按钮类型',
		dispOrder : '9',
		addController : '2',
		queryController : '0',
		nullable : '1',
		dispType : '3',
		showController : '1',
		tabName : 'sys_menu',
		dataType : '5',
		colName : 'button_type',
		editController : '2',
	}, {
		aliasColName : '按钮显示类型',
		dispOrder : '10',
		addController : '2',
		queryController : '0',
		nullable : '1',
		dispType : '1',
		showController : '1',
		tabName : 'sys_menu',
		dataType : '1',
		colName : 'button_show_type',
		editController : '2',
	}, {
		aliasColName : '排列顺序',
		dispOrder : '11',
		addController : '0',
		queryController : '0',
		nullable : '0',
		dispType : '1',
		showController : '1',
		tabName : 'sys_menu',
		dataType : '5',
		colName : 'disp_order',
		editController : '0',
	}, {
		aliasColName : '图标',
		dispOrder : '12',
		addController : '2',
		queryController : '0',
		nullable : '1',
		dispType : '1',
		showController : '1',
		tabName : 'sys_menu',
		dataType : '1',
		colName : 'icon',
		editController : '2',
	}, {
		aliasColName : '是否可见',
		dispOrder : '13',
		addController : '2',
		queryController : '0',
		nullable : '0',
		dispType : '3',
		showController : '1',
		tabName : 'sys_menu',
		dataType : '5',
		colName : 'visible',
		editController : '2',
	}],

	//SysFldVal信息
	sysFldVal: {
		visible: [
		{
			dispOrder : 1,
			dbVal : 1,
			tabName : 'sys_menu',
			colName : 'visible',
			dispVal : '显示',
		}, {
			dispOrder : 2,
			dbVal : 0,
			tabName : 'sys_menu',
			colName : 'visible',
			dispVal : '不显示',
		}],
		menu_type: [
		{
			dispOrder : 1,
			dbVal : 1,
			tabName : 'sys_menu',
			colName : 'menu_type',
			dispVal : 'ManagePage',
		}],
		button_type: [
		{
			dispOrder : 1,
			dbVal : 110,
			tabName : 'sys_menu',
			colName : 'button_type',
			dispVal : '表格上',
		}, {
			dispOrder : 2,
			dbVal : 111,
			tabName : 'sys_menu',
			colName : 'button_type',
			dispVal : '表格上必选一',
		}, {
			dispOrder : 3,
			dbVal : 120,
			tabName : 'sys_menu',
			colName : 'button_type',
			dispVal : '表格右',
		}, {
			dispOrder : 4,
			dbVal : 130,
			tabName : 'sys_menu',
			colName : 'button_type',
			dispVal : '表格上右',
		}, {
			dispOrder : 5,
			dbVal : 131,
			tabName : 'sys_menu',
			colName : 'button_type',
			dispVal : '表格上右必选一',
		}, {
			dispOrder : 6,
			dbVal : 210,
			tabName : 'sys_menu',
			colName : 'button_type',
			dispVal : '树上',
		}, {
			dispOrder : 7,
			dbVal : 211,
			tabName : 'sys_menu',
			colName : 'button_type',
			dispVal : '树上必选一',
		}],
		type: [
		{
			dispOrder : 1,
			dbVal : 1,
			tabName : 'sys_menu',
			colName : 'type',
			dispVal : '菜单',
		}, {
			dispOrder : 2,
			dbVal : 2,
			tabName : 'sys_menu',
			colName : 'type',
			dispVal : '按钮',
		}],
	},
};